### ISSUE TITLE
Electrical scheme

### ISSUE THREAD

**Issue by Wobak** [sylvaing/shelly-pool-pump#7]
Hello and thank you for this;

I am considering buying a Shelly one for this, but I'm not exactly sure I understand how everything is connected. 

I have a pump, I can buy a DS18b20 sensor, but I'm not sure what should be connected where.

Would it be possible to either draw or have picture on how you connected everything?

Thanks !

**Comment by sylvaing** [comment]
sorry i d'ont have electric schéma to connect shelly to your dumP.
For ds18b20, this version doesn't use adon sensor, you post provide temp via Home hassitant and mqtt. But I work on new version with shelly plus adon to use native ds28b20 directly connecter on shelly.
Stay tune, I think I win push a branch in alpha test.
Stay tuned !

**Comment by sylvaing** [comment]
you can look at shellyaddon branch
